# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_projet', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('agent_membres', models.ManyToManyField(to='agent.Agent')),
            ],
            options={
                'ordering': ['nom_du_projet'],
            },
        ),
        migrations.CreateModel(
            name='ProjetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='agent.Agent')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projet.Projet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projetmember',
            unique_together=set([('projet', 'agent')]),
        ),
    ]
