# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
