# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('image', models.ImageField(default='../static/images/profile.png', upload_to='pass_port')),
                ('date_de_naissance', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('Feminin', 'FEMININ'), ('Maxculin', 'MAXCULIN')], max_length=300)),
                ('etat_civil', models.CharField(choices=[('Marié', 'MARIE'), ('Celibataire', 'CELIBATAIRE')], max_length=300)),
                ('nbr_enfant', models.CharField(max_length=2)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('primaire', models.CharField(max_length=300)),
                ('secondaire', models.CharField(max_length=300)),
                ('universitaire', models.CharField(max_length=300)),
                ('formation', models.TextField(blank=True)),
                ('autres', models.TextField(blank=True)),
                ('langue', models.CharField(max_length=200)),
                ('maitrise', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('centre_interet', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'ordering': ['nom', 'post_nom', 'prenom'],
            },
        ),
    ]
